name = "XPS Core";
// picture = "logo_xps.paa";
actionName = "Website";
action = "https://github.com/XPS-Group/XPS_A3";
description = "Issues: https://github.com/XPS-Group/XPS_A3/issues";
// logo = "logo_xps.paa";
// logoOver = "logo_xps.paa";
tooltip = "eXtensible Project System - Core";
tooltipOwned = "eXtensible Project System";
overview = "pre-Alpha";
author = "XPS Group";
// overviewPicture = "logo_cba_ca.paa";
overviewText = "eXtensible Project System - pre-Alpha";
overviewFootnote = "<br /><br /><t color='#999999'>This content is a work in progress.<t />";