name = "XPS [PROJECT] v[0.0.0]-alpha";
actionName = "Website";
action = "https://github.com/XPS-Group/XPS_A3";
description = "Issues: https://github.com/XPS-Group/XPS_A3/issues";
logo = "icon_xps_[ADDON].paa";
logoOver = "icon_xps_[ADDON].paa";
tooltip = "eXtensible Project System - [PROJECT]";
tooltipOwned = "eXtensible Project System - [PROJECT]";
overview = "XPS v[0.0.0]-Alpha<br /><br /><t color='#999999'>This content is a work in progress.<t />";
author = "XPS Group";
picture = "logo_xps_[ADDON].paa";
